### ISSUE TITLE
Issue with offsets in ZICMP predict

### ISSUE THREAD

**Issue by andrewraim** [lotze/COMPoissonReg#10]
The ZICMP `predict` function initially had a mistake when support for offsets was added. This mistake is included in version v0.7.0, but has subsequently been fixed in the master branch.

Here are steps to reproduce the issue.
```r
data(couple)
zicmp.out = glm.cmp(UPB ~ EDUCATION + ANXIETY, formula.nu = ~ 1,
	formula.p = ~ EDUCATION + ANXIETY, data=couple)
print(zicmp.out)

new.data = data.frame(EDUCATION = round(1:20 / 20), ANXIETY = seq(-3,3,
	length.out = 20))
predict(zicmp.out, newdata=new.data)
```

This results in the output
```
Error in fitted.zicmp.internal(X, S, W, object$beta, object$gamma, object$zeta,  : 
  dims [product 20] do not match the length of object [387]
In addition: Warning message:
In X %*% beta + off.x :
  longer object length is not a multiple of shorter object length
Called from: fitted.zicmp.internal(X, S, W, object$beta, object$gamma, object$zeta, 
    object$off.x, object$off.s, object$off.w)
```

Until the corrected code gets released, here is a workaround for the typical case when the user has not opted to use offsets. 

```r
# Manually set the saved offsets in zicmp.out to be 0 to be compatible with the data in new.data
zicmp.out$off.x = 0
zicmp.out$off.s = 0
zicmp.out$off.w = 0
predict(zicmp.out, newdata = new.data)
```

If offsets are required, they cannot be specified to `predict` via `newdata` in v0.7.0. Code to work around this is more involved. If anyone urgently needs this, let me know.

**Comment by andrewraim** [comment]
Copied the corrected `predict` functions from master branch to v0.7.1.

**Comment by TanasitThai** [comment]
i try to use predict() by new data in ZICMP model but have a problem pls help me 
![image](https://user-images.githubusercontent.com/81686541/113134693-561ee580-924b-11eb-88f8-c60693a904f7.png)

**Comment by TanasitThai** [comment]
My purpose need to make prediction model by train data and test performance of model predict by test data. 
Now I'm doing same method with another count model such as ZIP ZINB but they still work . only ZICMP is not work I don't know why 

this my sample
![image](https://user-images.githubusercontent.com/81686541/113135242-15739c00-924c-11eb-9281-98ee0878fc0c.png)

**Comment by TanasitThai** [comment]
My purpose need to make prediction model by train data (80%) and test performance of model predict by test data (20%).
Now I'm doing same method ( predict() ) with another count model such as ZIP ZINB but they still work . only ZICMP it doesn't work  I don't know why? Thank you so much.
![image](https://user-images.githubusercontent.com/81686541/113136537-aeef7d80-924d-11eb-9ae8-1cd4f0ce0ff7.png)
train data n = 200 independent variable =7
![image](https://user-images.githubusercontent.com/81686541/113142007-9a62b380-9254-11eb-8e7e-93b7b4f44b16.png)
test data  n = 50   independent variable =7
![image](https://user-images.githubusercontent.com/81686541/113142269-e4e43000-9254-11eb-8184-5cba23e6e000.png)

**Comment by andrewraim** [comment]
Dear TanasitThai,

Could you supply a minimal working example in plain text rather than screenshots? That will be very helpful to reproduce your issue.

Thanks,
Andrew
