### ISSUE TITLE
More digits of accuracy in Euler–Mascheroni constant

### ISSUE THREAD

**Issue by Derek-Jones** [lotze/COMPoissonReg#3]
The C++ function cmp_allprobs needsh more digits of accuracy in its Euler–Mascheroni constant:
0.57721566490153286060651209008240243104215933593992

**Comment by andrewraim** [comment]
Thanks for the suggestion, despite this very slow reply. We will leave the constant at the current level of precision for now. The method of computing CMP probabilities - which is also used to truncate series in the normalizing constant - should be overhauled in the not-too-distant future.
