### ISSUE TITLE
Check nu > 0

### ISSUE THREAD

**Issue by Derek-Jones** [lotze/COMPoissonReg#4]
The C++ function cmp_allprobs needs to check that nu > 0

Calling dcmp with nu < 0 (a silly mistake I made) soaked up all the cpu time on my machine, swapped for a long time and eventually killed the process.

I need to be protected from myself.

**Comment by andrewraim** [comment]
Added checks for `nu` along with `lambda >= 0` and `0 <= p <= 1`. They will be in the next release
