### ISSUE TITLE
coef(mod, what="lambda") does not return desired value

### ISSUE THREAD

**Issue by Derek-Jones** [lotze/COMPoissonReg#6]
The call: coef(mod, what="lambda") does not return desired value.

I am using the code exp(mod$beta), and would like to use the 'standard' approach via  coef.

**Comment by andrewraim** [comment]
Finally addressing this in branch `vignette`, which should be included in 0.8 release. The `predict` functions are updated to take a `type` argument, which can be `"response"` to get fitted response value or `"link"` to get a data frame with columns `lambda`, `nu` and `p` (if zero-inflated regression is used). This was inspired by the interface of the `predict.glm` function, so hopefully you will find it intuitive.
